export const ALL_HEROES_REQUEST = "ALL_HEROES_REQUEST";
export const ALL_HEROES_SUCCESS = "ALL_HEROES_SUCCESS";
export const ALL_HEROES_FAIL = "ALL_HEROES_FAIL";

export const HERO_DETAILS_REQUEST = "HERO_DETAILS_REQUEST";
export const HERO_DETAILS_SUCCESS = "HERO_DETAILS_SUCCESS";
export const HERO_DETAILS_FAIL = "HERO_DETAILS_FAIL";

//Admin
export const ADMIN_HEROES_REQUEST = "ADMIN_HEROES_REQUEST";
export const ADMIN_HEROES_SUCCESS = "ADMIN_HEROES_SUCCESS";
export const ADMIN_HEROES_FAIL = "ADMIN_HEROES_FAIL";

export const NEW_HERO_REQUEST = "NEW_HERO_REQUEST";
export const NEW_HERO_SUCCESS = "NEW_HERO_SUCCESS";
export const NEW_HERO_RESET = "NEW_HERO_RESET";
export const NEW_HERO_FAIL = "NEW_HERO_FAIL";

export const UPDATE_HERO_REQUEST = "UPDATE_HERO_REQUEST";
export const UPDATE_HERO_SUCCESS = "UPDATE_HERO_SUCCESS";
export const UPDATE_HERO_RESET = "UPDATE_HERO_RESET";
export const UPDATE_HERO_FAIL = "UPDATE_HERO_FAIL";

export const DELETE_HERO_REQUEST = "DELETE_HERO_REQUEST";
export const DELETE_HERO_SUCCESS = "DELETE_HERO_SUCCESS";
export const DELETE_HERO_RESET = "DELETE_HERO_RESET";
export const DELETE_HERO_FAIL = "DELETE_HERO_FAIL";

//User
export const MY_HEROES_REQUEST = "MY_HEROES_REQUEST";
export const MY_HEROES_SUCCESS = "MY_HEROES_SUCCESS";
export const MY_HEROES_FAIL = "MY_HEROES_FAIL";

export const UPDATE_MY_HERO_REQUEST = "UPDATE_MY_HERO_REQUEST";
export const UPDATE_MY_HERO_SUCCESS = "UPDATE_MY_HERO_SUCCESS";
export const UPDATE_MY_HERO_RESET = "UPDATE_MY_HERO_RESET";
export const UPDATE_MY_HERO_FAIL = "UPDATE_MY_HERO_FAIL";

export const DELETE_MY_HERO_REQUEST = "DELETE_MY_HERO_REQUEST";
export const DELETE_MY_HERO_SUCCESS = "DELETE_MY_HERO_SUCCESS";
export const DELETE_MY_HERO_RESET = "DELETE_MY_HERO_RESET";
export const DELETE_MY_HERO_FAIL = "DELETE_MY_HERO_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
